title: 안녕하세요! 송민우의 포트폴리오입니다.
description: > # this means to ignore newlines until "baseurl:"
  송민우의 폴트폴리오
permalink: ':title/'
baseurl: "/FadakPortfolio" # the subpath of your site, e.g. /blog
url: "fadak0828.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Minwoo Song # add your name
author-img: minwoosong.jpg # add your photo
about-author: TypeScript, JavaScript, Angular, React, React-Native, Java, C#, Unity, Blender # add description
social-github: fadak0828 # add your Github handle
social-email: devfadakworld@gmail.com # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
